theme: jekyll-theme-cayman
title: MorpheApp Patched APKs
description: Pre‑patched YouTube & YT Music APKs — safer, ad‑free, and updated daily. No ReVanced manager needed.
baseurl: /MorpheApp-Artifacts
show_downloads: false
plugins:
  - jekyll-sitemap
